[workspace]
resolver = "3"
members = [
    "askit-cozodb-agents",
    "askit-llm-agents",
    "askit-rhai-agents",
    "askit-std-agents",
    "agent-stream-kit",
]

[workspace.package]
edition = "2024"
authors = ["Akira Ishino <akira@lumilab.jp>"]
license = "Apache-2.0 OR MIT"
